services:
  fraude-postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: fraude_db
      POSTGRES_USER: fraude_user
      POSTGRES_PASSWORD: fraude_pass
    ports:
      - "5435:5432"
    volumes:
      - fraude_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fraude_user -d fraude_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - fraude-net

  fraude:
    build: .
    ports:
      - "8084:8084"
    environment:
      FRAUDE_DB_HOST: fraude-postgres
      FRAUDE_DB_PORT: 5432
      FRAUDE_DB_NAME: fraude_db
      FRAUDE_DB_USER: fraude_user
      FRAUDE_DB_PASSWORD: fraude_pass
    depends_on:
      fraude-postgres:
        condition: service_healthy
    networks:
      - fraude-net

networks:
  fraude-net:
    driver: bridge

volumes:
  fraude_postgres_data:
