INSERT INTO fraude.typology_catalog (id, name, description, default_severity, requires_review) VALUES
    ('AUTH_ANOMALY',         'Anomalia de Autenticacion',
     'Patron irregular en intentos de autenticacion',            'SUSPICIOUS',  TRUE),
    ('BIOMETRIC_MISMATCH',   'Discrepancia Biometrica',
     'Fallo de coincidencia biometrica en autenticacion',        'SUSPICIOUS',  TRUE),
    ('DUPLICATE_VOTE',       'Intento de Voto Duplicado',
     'Misma identidad intenta votar mas de una vez',             'CRITICAL',    TRUE),
    ('BURST_DETECTED',       'Rafaga de Eventos',
     'Volumen anomalo de eventos en ventana temporal corta',     'SUSPICIOUS',  TRUE),
    ('TABLE_OUTLIER',        'Mesa con Comportamiento Atipico',
     'Volumen de operaciones fuera de la norma respecto a mesas pares', 'SUSPICIOUS', TRUE),
    ('LB_EMERGENCY_MOD',     'Modificacion de Emergencia Lista Blanca',
     'Alteracion de lista blanca via ruta de emergencia',        'CRITICAL',    TRUE),
    ('CENSUS_FREEZE_VIOLATION','Violacion de Congelamiento de Censo',
     'Intento de modificacion posterior al congelamiento',       'CRITICAL',    TRUE),
    ('E14_ANOMALY',          'Anomalia en Acta E14',
     'Inconsistencia detectada en el ciclo de vida del acta',    'SUSPICIOUS',  TRUE),
    ('AUTH_CHAIN_BREAK',     'Rotura de Cadena de Auditoria',
     'Hash chain verification failed en audit log',              'CRITICAL',    TRUE),
    ('ACCESS_VIOLATION',     'Violacion de Acceso',
     'Intento de acceso a recurso no autorizado',                'SUSPICIOUS',  TRUE);
